### ISSUE TITLE
Cant install apps

### ISSUE THREAD

**Issue by Tobe2d** [pinokiocomputer/pinokio#38] opened 2023-10-16 15:06 UTC
Hi, not sure if this been asked here before but I need help sorting this out.

I cant install any app as it show this:

![image](https://github.com/pinokiocomputer/pinokio/assets/4099839/7a1e1c49-75e7-448a-a835-a37480344767)
I have all those already installed and I use them everyday.
However, when i press install it does install those missing and I get this:
![image](https://github.com/pinokiocomputer/pinokio/assets/4099839/27ba5257-fbdf-4da2-9961-7fafe417667a)

pressing ok it take me back to this:
![image](https://github.com/pinokiocomputer/pinokio/assets/4099839/7a1e1c49-75e7-448a-a835-a37480344767)

As if it is looping.

How to solve this?

**Comment by ossafe** [comment] 2023-10-27 02:30
It might not help, but I had the same problem updating from a real old version. Ended up I needed to 

- dragged my entire pinokio directory out, 
- uninstalled the app, 
- completely uninstall all traces of visual studio (I had that as uninstalled in my list too)
- rebooted, 
- reinstalled the app, 
- reinstalled my spaces,
- reinstalled the version of VS I normally use,
- then copied out the models and customisations from the previously saved tree into the new one.

**Comment by arsen3d** [comment] 2023-10-27 21:56
Fixed in version
https://github.com/pinokiocomputer/pinokio/releases/tag/0.1.23

**Comment by andyg2** [comment] 2023-11-01 04:02
I have this exact problem in Pinokio 0.1.35
Conda and Registry installed but everything else in an install loop.
I see the conda_hook command fire for each of the missing components however they are literally 1 second apart without any other signs of progress. I've tried uninstalling, rebooting, reinstalling, I even tried installing as Administrator

Lastly when I try to submit a bug report it asks to download log.txt or log.html but the log is not exported but I've attached stdout from the logs directory.
[stdout.txt](https://github.com/pinokiocomputer/pinokio/files/13223283/stdout.txt)

Microsoft Windows [Version 10.0.19045.3570]

**Comment by deronkel82** [comment] 2023-11-01 07:03
same here. 
Version
0.1.35 (server: 0.0.393)

**Comment by eyalfrish** [comment] 2023-11-02 09:10
Same here :( -
Version
0.1.40 (server: 0.0.399)

**Comment by gremaldi** [comment] 2023-11-04 10:43
same issue with:
0.1.47 (server: 0.0.406)
on windows 10

**Comment by joshfedo** [comment] 2023-11-15 17:26
Same issue after updating from v1.X to 2.5. 

Fixed this by uninstalling pinokio , deleting the pinokio directory, rebooting, and reinstalling. 

With so many changes happening in pinokio  so quickly i'd imagine a fresh install is going to be what most people need to do to fix this.

**Comment by AdamWhiteC** [comment] 2023-12-01 20:22
使用管理员模式打开pinokio，就可以解决问题了。

**Comment by jgforbes** [comment] 2023-12-05 03:01
Same error on Fedora 38 with Pinokio v0.2.7

$eval "$(conda shell.bash hook)" && conda activate base && conda install -y -c conda-forge git git-lfs

NoBaseEnvironmentError: This conda installation has no default base environment. Use
'conda create' to create new environments and 'conda activate' to
activate environments.


(base) [bin]$ [ bin]$ eval "$(conda shell.bash hook)" && conda activate base && conda install -y -c conda-forge p7zip

NoBaseEnvironmentError: This conda installation has no default base environment. Use
'conda create' to create new environments and 'conda activate' to
activate environments.


(base) [bin]$ [jgf@bigdog2 bin]$ eval "$(conda shell.bash hook)" && conda activate base && conda install nodejs -y -c conda-forge

NoBaseEnvironmentError: This conda installation has no default base environment. Use
'conda create' to create new environments and 'conda activate' to
activate environments.

**Comment by mattlxdesign** [comment] 2023-12-10 23:31
Ditto on Manjaro with Pinokio version 0.2.16

The best I can work out from trying to manually install git, zip and nodejs in the Pinokio installed miniconda environment is that I have anaconda installed using my distribution package manager and I can't get the Pinokio miniconda environment to activate correctly. If I 
`path_to/Pinokio/bin/miniconda/bin/conda init --all`
I  get
> no change     ~/.bashrc

> 

When I activate conda from the Pinokio/bin directory, my package manager version of conda is activated.
Therefore I suspect Pinokio can't activate the miniconda version it has supplied, Therefore Pinokio gets stuck.....
Is there a way to set Pinokio to use a system version of conda? I have used the AppImage installer

**Comment by SorrentinoPro** [comment] 2023-12-14 17:42
I do have similar issues on windows 11 pinokio v 0.2.7 (lts today)
like the picture highlights asked me to look for dialog but no system dialog popping up reqyuesting permission, just pinokio dialog saying compleated successfully. 
Is there another way to give permission and solve this problem?

![image](https://github.com/pinokiocomputer/pinokio/assets/25386347/c3e4404c-5305-4b6a-86b6-4cddb2c8f183)

**Comment by KarimElgazaar** [comment] 2023-12-23 06:05
i had this problem and it took 2 hours to find the cause. it happens because the file path of the installation of conda has a space in my case it was in the name of the user so i changed the installation path of pinokio from disk c to d where there the path doesnt contain thew users name and it worked

**Comment by D4zedC0der** [comment] 2024-01-04 10:24
My solution was v. similar. There were spaces in my PATH environment variable which I needed to remove. After that, the conda install commands actually worked.

**Comment by 6Morpheus6** [comment] 2024-02-09 07:08
For most of these issues you will find a solution in this article.
[git, zip, conda: node.js can't be installed](https://github.com/6Morpheus6/pinokio-wiki?tab=readme-ov-file#git-zip-conda-nodejs-cant-be-installed)

**Comment by Rodriq** [comment] 2024-05-10 06:14
> i had this problem and it took 2 hours to find the cause. it happens because the file path of the installation of conda has a space in my case it was in the name of the user so i changed the installation path of pinokio from disk c to d where there the path doesnt contain thew users name and it worked

Thank you. This helped

**Comment by Skettalee** [comment] 2024-05-11 11:42
this didn't work at all almost a year ago and its the same now. Wy do people like this? Im having the same error of for any single ai tool i try to install and it just keeps making popping sounds and eventually returns with only 2 of the 5 or 6 things it was set t install and says the same error message. Noone figured this out?

**Closed** 2024-06-12 19:11 UTC

**Comment by MaKiPL** [comment] 2024-09-28 11:57
> After (many hours) - make sure you set an environmental variable For Windows: P:\pinokio\bin\miniconda\condabin (or whatever your drive/path may be) System Properties -> Environmental Variables (at the bottom of that window pane) -> select Path -> click Edit -> New -> put your path in there
> 
> Close Pinokio -> reopen, and try again

Worked, but Pinokio should be handling this automatically. In my opinion, this should NOT be closed @Tobe2d
